import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import QueryProvider from './providers/QueryProvider'
import { MSWProvider } from './providers/MSWProvider'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex justify-center`}
      >
        <MSWProvider>
          <QueryProvider>
            <div className="min-h-screen w-full max-w-[430px] bg-white shadow-lg">
              {children}
            </div>
          </QueryProvider>
        </MSWProvider>
      </body>
    </html>
  )
}
